In [1]:
import pandas as pd
import numpy as np

df = pd.read_csv("Social_Network_Ads.csv")
X = df.iloc[:,1:-1]
X = pd.get_dummies(X).iloc[:,:-1].values
y = df.iloc[:,-1].values

In [2]:
df.head(3)

User ID  Gender  Age  EstimatedSalary  Purchased
0  15624510    Male   19            19000          0
1  15810944    Male   35            20000          0
2  15668575  Female   26            43000          0

In [3]:
X

array([[   19, 19000,     0],
       [   35, 20000,     0],
       [   26, 43000,     1],
       ...,
       [   50, 20000,     1],
       [   36, 33000,     0],
       [   49, 36000,     1]])

In [4]:
from logreg_nr_v2 import LogisticRegression
lr = LogisticRegression(X, y)
res = lr.logistic_regression_newton()

In [5]:
preds = lr.y_pred()

In [11]:
preds[:50]

array([0.00070614, 0.03146107, 0.00633407, 0.01327757, 0.00560853,
       0.01911414, 0.03474353, 0.56600386, 0.00485443, 0.10706977,
       0.02395961, 0.00877106, 0.01018643, 0.01461724, 0.00550727,
       0.06522989, 0.40102426, 0.30180933, 0.37078632, 0.41282276,
       0.27200742, 0.53483   , 0.60320308, 0.21110045, 0.32936666,
       0.35814946, 0.54539049, 0.36520655, 0.01779807, 0.01156891,
       0.08263355, 0.19892651, 0.00072819, 0.01050775, 0.05886113,
       0.04023506, 0.01901572, 0.02778474, 0.01800982, 0.00519018,
       0.00312261, 0.0428956 , 0.44516812, 0.00821055, 0.0436287 ,
       0.00188739, 0.02541427, 0.01191894, 0.39624207, 0.10026201])

In [6]:
hats = lr.y_hat()

In [10]:
hats[:50]

array([0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0])

In [12]:
lr.coeffs_

array([-1.24497907e+01,  2.36969401e-01,  3.64411904e-05, -3.33843388e-01])

In [13]:
lr.confusion_matrix()

array([[237,  20],
       [ 39, 104]])

In [14]:
print(f"""
Sensitivity : {lr.sensitivity()}
Specificity : {lr.specificity()}
Accuracy : {lr.accuracy()}
Precision : {lr.precision()}
F1_score : {lr.f1_score()}
""")


Sensitivity : 0.7272727272727273
Specificity : 0.9221789883268483
Accuracy : 0.8525
Precision : 0.8387096774193549
F1_score : 0.7790262172284644



In [15]:
print(lr.roc_auc())

0.9274033359636473
